### ISSUE TITLE
Any chance to install it via conda / miniconda?

### ISSUE THREAD

**Issue by AntonioBaeza** [hhandika/segul#26]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hhandika** [comment]
Hi @AntonioBaeza, we have not yet had an option to install from Bioconda. We are looking into adding this option soon. It was not a priority because we preferred python developers to use the python library, PySEGUL. The overhead is minimal. We aware some of SEGUL potential users may prefer to install through conda when they already have conda installed. We will do our best to speed up this process. To help you keep track, I will keep this issue open until SEGUL is approved to distribute through bioconda.

**Comment by AntonioBaeza** [comment]
Thanks!

**Comment by hhandika** [comment]
Hi @AntonioBaeza, Good news. I worked on it today. It's available in Bioconda now: `conda install bioconda::segul`.  We will update the documentation later.

**Comment by AntonioBaeza** [comment]
Great! I will try it in short, thanks again! Antonio
